from google import genai
import os
from dotenv import load_dotenv
from PromptSelector import get_prompt_for_current_time
from event_detector import CONTENT_QUOTE, build_quote_event_instruction, get_today_event

load_dotenv()

client = genai.Client(
    api_key=os.getenv("GEMINI_API_KEY")
)

def generate_quote(record_history=True):
    """
    Generate content based on current time.
    Uses time-based prompt selection to save tokens and ensure variety.
    """
    # Get the appropriate prompt for current time
    prompt = get_prompt_for_current_time(record_history=record_history)

    # Optional enhancement: if today is a configured special event,
    # add event context without changing the default random logic.
    event = get_today_event(content_type=CONTENT_QUOTE)
    if event:
        prompt += build_quote_event_instruction(event)
    
    # Generate content using Gemini
    interaction = client.interactions.create(
        model="gemini-3.6-flash",
        input=prompt
    )

    return interaction.output_text or ""


def generate_quote_caption(quote_text, event=None):
    """Generate an engaging, relatable caption to accompany a quote image.

    Uses Simple English, never repeats the quote verbatim, and reads like
    a warm hook people want to save and share. An active event adds a subtle
    seasonal touch when relevant.
    """
    event_context = ""
    if event:
        name = (event.get("name") or "").strip()
        if name:
            event_context = (
                f"\nToday is related to {name}. If it fits naturally, weave in a "
                "gentle nod to it without overdoing it."
            )

    prompt = f"""You are a social media caption writer for "Aesthetic Vibes" - a page for lost souls finding their way home through words.

The quote image below is about to be posted. Write ONE warm, engaging caption (1-2 short sentences, max 25 words) that adds a fresh feeling to the quote instead of repeating it.

Rules:
- Use the simplest everyday words only - like saying it to a friend over chai. No fancy, heavy, or uncommon words.
- SIMPLE ENGLISH the South Asian audience can easily understand.
- Relatable, warm, human tone - a small hook that makes people want to save, share, or comment.
- Do NOT repeat the quote word-for-word.
- Do NOT use hashtags, emojis, labels, or explanations.
{event_context}

Quote:
"{quote_text}"

Return only the caption text.
"""
    # Generate the caption using Gemini
    interaction = client.interactions.create(
        model="gemini-3.6-flash",
        input=prompt
    )

    return (interaction.output_text or "").strip()


def build_quote_post_caption(quote_text, event=None, base_caption=""):
    """Build the final social caption for a quote post.

    1) Uses an AI-generated engaging caption from Gemini.
    2) Uses an optional caller-provided base caption if the AI returns nothing empty.
    3) Appends reel-style hashtags generated by `generate_hashtags(event=event)`.

    Returns a single formatted caption string ready for upload.
    """
    caption = (generate_quote_caption(quote_text, event=event) or "").strip()
    if not caption:
        caption = (base_caption or "").strip()

    # Re-use the same hashtag generator the reels pipeline uses.
    from Reels.hashtag_generation import generate_hashtags

    hashtags = (generate_hashtags(event=event) or "").strip()

    parts = [part for part in (caption, hashtags) if part.strip()]
    return "\n\n".join(parts)