import random

# Always included
FIXED_HASHTAGS = [
    "#LifeQuotes",
    "#LifeLessons",
    "#Reels",
]

# Random pool
HASHTAG_POOL = [
    "#Quotes",
    "#Quote",
    "#QuoteOfTheDay",
    "#DailyQuote",
    "#DailyQuotes",
    "#QuoteLife",
    "#InspirationalQuotes",
    "#MotivationalQuotes",
    "#PositiveQuotes",
    "#WisdomQuotes",
    "#PowerfulQuotes",
    "#MeaningfulQuotes",
    "#DeepQuotes",
    "#FamousQuotes",
    "#QuoteLover",
    "#Words",
    "#WordsOfWisdom",
    "#WiseWords",
    "#Thoughts",
    "#DeepThoughts",
    "#DailyWisdom",
    "#Life",
    "#LifeAdvice",
    "#LifeJourney",
    "#LifeMotivation",
    "#LifeInspiration",
    "#LifeTips",
    "#Advice",
    "#GoodAdvice",
    "#Motivation",
    "#Inspiration",
    "#Success",
    "#SuccessMindset",
    "#Growth",
    "#GrowthMindset",
    "#SelfGrowth",
    "#PersonalGrowth",
    "#SelfImprovement",
    "#SelfDevelopment",
    "#BetterYourself",
    "#Mindset",
    "#PositiveMindset",
    "#PositiveThinking",
    "#Discipline",
    "#Habits",
    "#Focus",
    "#Consistency",
    "#Family",
    "#FamilyFirst",
    "#FamilyLove",
    "#FamilyTime",
    "#FamilyGoals",
    "#Parents",
    "#Parenting",
    "#ParentingTips",
    "#Relationship",
    "#Relationships",
    "#Love",
    "#Respect",
    "#Trust",
    "#Kindness",
    "#Gratitude",
    "#Togetherness",
    "#Home",
    "#Marriage",
    "#HealthyRelationships",
    "#MentalHealth",
    "#InnerPeace",
    "#Peace",
    "#Healing",
    "#HealingJourney",
    "#SelfCare",
    "#SelfLove",
    "#EmotionalHealing",
    "#Mindfulness",
    "#CalmMind",
    "#Hope",
    "#Happiness",
    "#Joy",
    "#Positivity",
    "#BeKind",
    "#DailyMotivation",
    "#NeverGiveUp",
    "#KeepGoing",
    "#DreamBig",
    "#BelieveInYourself",
    "#HardWork",
    "#SuccessQuotes",
    "#GoalSetter",
    "#WorkHard",
    "#MindsetMatters",
    "#StayStrong",
    "#BeBetter",
    "#WinTheDay",
    "#Inspirational",
    "#Inspire",
    "#InspireDaily",
    "#InspirationalWords",
    "#DailyInspiration",
    "#Encouragement",
    "#Faith",
    "#Believe",
    "#Purpose",
    "#Vision",
    "#Deep",
    "#RealTalk",
    "#Truth",
    "#Reality",
    "#TruthOfLife",
    "#Emotions",
    "#Feelings",
    "#Heart",
    "#Soul",
    "#InnerStrength",
    "#Reflection",
    "#SelfReflection",
    "#LessonsLearned",
    "#WakeUpCall",
    "#InstagramReels",
    "#ReelsInstagram",
    "#Reel",
    "#ReelVideo",
    "#ReelCreator",
    "#ReelLife",
    "#Explore",
    "#ExplorePage",
    "#ExploreMore",
    "#Viral",
    "#Trending",
    "#TrendingReels",
    "#ContentCreator",
    "#Creators",
    "#DailyContent",
    "#ShortVideo",
    "#VideoOfTheDay",
    "#Productivity",
    "#Goals",
    "#GoalSetting",
    "#Leadership",
    "#BusinessMindset",
    "#Entrepreneur",
    "#Winning",
    "#Ambition",
    "#DisciplineEqualsFreedom",
    "#LearnEveryDay",
    "#KeepLearning",
    "#DailyReminder",
    "#DailyThought",
    "#Reminder",
    "#SimpleLiving",
    "#HealthyMind",
    "#PositiveVibes",
    "#GoodVibes",
    "#Humble",
    "#Wisdom",
    "#Character",
    "#RespectEveryone",
    "#Humanity",
    "#KindnessMatters",
    "#LiveBetter",
    "#LiveInspired",
    "#BeYourBest",
    "#LifeIsBeautiful",
    "#ChooseKindness",
    "#StayPositive",
    "#BeHappy",
]


def generate_hashtags(min_count=20, max_count=23):
    """
    Returns a string of 18-20 hashtags.
    Always includes:
        #LifeQuotes
        #LifeLessons
        #Reels
    """

    if min_count < len(FIXED_HASHTAGS):
        raise ValueError("min_count must be at least 3")

    total = random.randint(min_count, max_count)

    random_tags = random.sample(
        HASHTAG_POOL,
        total - len(FIXED_HASHTAGS)
    )

    hashtags = FIXED_HASHTAGS + random_tags
    random.shuffle(hashtags)

    return " ".join(hashtags)


if __name__ == "__main__":
    print(generate_hashtags())